project:
  type: website
  #favicon: favicon.png
  resources:
    - "mazes.js"
    - "styles.css"

website:
  title: "Nicholas Michaud"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    highlight-style: dracula
    theme:
      - brite.css
    css: styles.css
    toc: false



